### ISSUE TITLE
Same project name causes confusion. 

### ISSUE THREAD

**Issue by hopeseekr** [TheDragonCode/simple-data-transfer-object#47]
My package was published a full 2 years before.

https://github.com/PHPExpertsInc/SimpleDTO

```
commit 44ab94a9e1f0d5117dd00dd60566fd004f44cca1
Author: Theodore R. Smith <theodore@phpexperts.pro>
Date:   Thu Mar 28 07:26:18 2019 -0500

    Pretty much everything. v0.99.
```

**Comment by andrey-helldar** [comment]
@hopeseekr,

1. there are a lot of such packages. Take the same Spatie Laravel Data.
2. This is the first time I have heard about your package.
3. Both my code and yours are distributed under the MIT license.
4. I wrote the code of this project from scratch.

Therefore, I don't understand the essence of the claim and the only thing I can assume is that you are trying to advertise your package at my expense.
